### ISSUE TITLE
Can we move react-paper-css from banjerr's github pages

### ISSUE THREAD

**Issue by ummahusla** [papercss/papercss-react#3]
Current demo URL: `https://banjerr.github.io/React-Paper-CSS-Page/`
We need to stick with org name, as we now moved demo to this page.
Preferably: `https://www.getpapercss.com/react` or something like this.

**Comment by Banjerr** [comment]
I've moved the demo to the org's repo, and deployed to GitHub pages. We can deploy this to a sub-directory as well, it's just a simple create-react-app. Not sure who owns that domain/hosting though

https://github.com/papercss/React-Paper-CSS-Page

**Comment by hasparus** [comment]
Can we close this issue? It appears to be done.
