### ISSUE TITLE
Create example folder or readme section

### ISSUE THREAD

**Issue by ummahusla** [papercss/papercss-react#7]

**Comment by Banjerr** [comment]
ive got a "demo" page started that I think would be good for this, just share that source code in a directory maybe? I'll transfer that over to this org this weekend, most likely

**Comment by kohlerm** [comment]
would be interested in the examples

**Comment by Banjerr** [comment]
@kohlerm these have been moved over to the org

https://papercss.github.io/React-Paper-CSS-Page/
https://github.com/papercss/React-Paper-CSS-Page
