### ISSUE TITLE
Need to update the link for the demo

### ISSUE THREAD

**Issue by Banjerr** [papercss/papercss-react#8]
Demo has been moved to the org, but I dont seem to have access to update this link

https://papercss.github.io/React-Paper-CSS-Page/

**Comment by ummahusla** [comment]
@Banjerr Thank you. @rhyneav can you please sort out this issue? 
Additionally, would be cool to move it to https://www.getpapercss.com/react or smth like this.

**Comment by Banjerr** [comment]
@rhyneav @ummahusla can one of y'all make me a maintainer, or perhaps update the link to the demo page in the top description? It's currently still pointing to the demo when it was on my GitHub page. 

We could also set this up on the https://www.getpapercss.com domain pretty easily (its just a very basic Create React App), but I don't have hosting/domain access.

**Comment by ummahusla** [comment]
Yeah, I created issue for this case #3 
@Banjerr I've just checked you have the write access, to the repo, I see nothing wrong making you as an admin 
@rhyneav Do you want me to update his access, or you will do it.

**Comment by rhyneav** [comment]
Just updated @Banjerr's access.
